### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [Hatrison/PacManGame#1]
1. Terrible code: https://github.com/Hatrison/PacManGame/blob/811b92423c3c1eeca1af2a1f1d2c52e7fa63b8cc/src/js/Enemy.js#L100-L110
See following:
```js
  isCollision(pacman) {
    const size = this.size / 2;
    const { x, y } = pacman;
    const x2 = this.x + size;
    const y2 = this.y + size;
    return this.x < x2 && x2 > x && this.y < y2 && y2 > y;
  }
```
2. Use collection instead of switch/case: https://github.com/Hatrison/PacManGame/blob/811b92423c3c1eeca1af2a1f1d2c52e7fa63b8cc/src/js/Enemy.js#L83-L93
3. Multiple nested loops and deeply enclosed if-statements are detected.
4. Multiline if-conditions are not readable
5. Hardcoded magic numbers

Need interview or refactoring to pass exams

**Comment by Hatrison** [comment]
Refactored

**Comment by Hatrison** [comment]
Добрый вечер, спасибо, что сделали код ревью.
Я отрефакторил код, исправил все недочеты. Можно получить оценку сейчас?
С уважением, Вадим Улановский!

пт, 13 янв. 2023 г. в 17:55, Timur Shemsedinov ***@***.***>:

**Comment by tshemsedinov** [comment]
How can I see diff, plz create pull-requests for future

**Comment by Hatrison** [comment]
I'm sorry, I'll study it in the future, thanks!
